Allow `template_path` field on inputs
elastic/package-registry pull request #655
Opened 2020-11-19 23:17 UTC by jen-huang

Follow up to https://github.com/elastic/package-spec/pull/79. Kibana needs `template_path` to ascertain which input template file to read from to build the agent YAML. This PR lets the registry serve that field at the input level, if defined.

2020-11-19 23:20 UTC, elasticmachine commented
## :broken_heart: Build Failed


<!-- BUILD BADGES-->
> _the below badges are clickable and redirect to their specific view in the CI or DOCS_
[![Pipeline View](https://img.shields.io/badge/pipeline-pipeline%20-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fpackage-registry%2FPR-655/detail/PR-655/1//pipeline) [![Test View](https://img.shields.io/badge/test-test-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fpackage-registry%2FPR-655/detail/PR-655/1//tests) [![Changes](https://img.shields.io/badge/changes-changes-green)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fpackage-registry%2FPR-655/detail/PR-655/1//changes) [![Artifacts](https://img.shields.io/badge/artifacts-artifacts-yellow)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fpackage-registry%2FPR-655/detail/PR-655/1//artifacts) [![preview](https://img.shields.io/badge/docs-preview-yellowgreen)](http://package-registry_655.docs-preview.app.elstc.co/diff)

<!-- BUILD SUMMARY-->
<details><summary>Expand to view the summary</summary>
<p>

#### Build stats

* Build Cause: `[Pull request #655 opened]`

* Start Time: 2020-11-19T23:17:56.724+0000

* Duration: 2 min 7 sec





</p>
</details>

<!-- TEST RESULTS IF ANY-->


<!-- STEPS ERRORS IF ANY-->


### Steps errors [![1](https://img.shields.io/badge/1%20-red)](https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Fpackage-registry%2FPR-655/detail/PR-655/1//pipeline)
  <details><summary>Expand to view the steps failures</summary>
  <p>

  
  
  
  
  
#### `Checks formatting / linting`
<ul>
<li>Took 0 min 8 sec . View more details on <a href="https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Ingest-manager/pipelines/package-registry/pipelines/PR-655/runs/1/steps/115/log/?start=0">here</a></li>
<li>Description: <code>mage -debug check</code></l1>
</ul>
  
  </p>
  </details>



<!-- LOG OUTPUT-->
### Log output

<details><summary>Expand to view the last 100 lines of log output</summary>
<p>

```
[2020-11-19T23:19:22.849Z]  > git merge 3bdd344faec70f7e2cd254c4920fabe9f555b99b # timeout=10
[2020-11-19T23:19:22.857Z]  > git rev-parse HEAD^{commit} # timeout=10
[2020-11-19T23:19:22.864Z]  > git config core.sparsecheckout # timeout=10
[2020-11-19T23:19:22.867Z]  > git checkout -f 0ab84fcb1c14e8d0ea80f37bbc99279f7c24b946 # timeout=15
[2020-11-19T23:19:22.922Z]  > git rev-parse --verify HEAD # timeout=10
[2020-11-19T23:19:22.925Z] Resetting working tree
[2020-11-19T23:19:22.925Z]  > git reset --hard # timeout=10
[2020-11-19T23:19:22.967Z]  > git clean -fdx # timeout=10
[2020-11-19T23:19:24.310Z] + git fetch https://****:****@github.com/elastic/package-registry.git +refs/pull/*/head:refs/remotes/origin/pr/*
[2020-11-19T23:19:26.269Z] Archiving artifacts
[2020-11-19T23:19:26.882Z] + git rev-parse HEAD
[2020-11-19T23:19:27.235Z] + git rev-parse HEAD
[2020-11-19T23:19:27.543Z] + git rev-parse origin/pr/655
[2020-11-19T23:19:27.582Z] [INFO] githubEnv: Found Git Build Cause: pr
[2020-11-19T23:19:27.794Z] Masking supported pattern matches of $GITHUB_TOKEN
[2020-11-19T23:19:28.738Z] [WARN] githubApiCall: The REST API call https://api.github.com/repos/elastic/package-registry/pulls/655/reviews return 0 elements
[2020-11-19T23:19:28.787Z] [INFO] githubPrCheckApproved: Title: Allow `template_path` field on inputs - User: jen-huang - Author Association: MEMBER
[2020-11-19T23:19:36.516Z] Stashed 1403 file(s)
[2020-11-19T23:19:36.599Z] Running in /var/lib/jenkins/workspace/_manager_package-registry_PR-655/src/github.com/elastic/package-registry
[2020-11-19T23:19:39.025Z] + gvm 1.13.0
[2020-11-19T23:19:44.311Z] export GOROOT="/var/lib/jenkins/workspace/_manager_package-registry_PR-655/.gvm/versions/go1.13.linux.amd64"
[2020-11-19T23:19:44.311Z] export PATH="/var/lib/jenkins/workspace/_manager_package-registry_PR-655/.gvm/versions/go1.13.linux.amd64/bin:$PATH"
[2020-11-19T23:19:44.671Z] + go get -u github.com/magefile/mage
[2020-11-19T23:19:46.948Z] + go get -u github.com/elastic/go-licenser
[2020-11-19T23:19:48.261Z] + go get -u golang.org/x/tools/cmd/goimports
[2020-11-19T23:19:53.910Z] + go get -u github.com/jstemmer/go-junit-report
[2020-11-19T23:19:54.901Z] Running in /var/lib/jenkins/workspace/_manager_package-registry_PR-655/src/github.com/elastic/package-registry
[2020-11-19T23:19:55.211Z] + mage -debug check
[2020-11-19T23:19:55.211Z] DEBUG: 23:19:54.955169 getting all non-mage files in .
[2020-11-19T23:19:55.471Z] DEBUG: 23:19:55.234123 found non-mage files artifacts.go||categories.go||favicon.go||handler.go||index.go||main.go||mime_types.go||package_index.go||search.go||static.go
[2020-11-19T23:19:55.472Z] DEBUG: 23:19:55.234157 marked file as non-mage: "artifacts.go"
[2020-11-19T23:19:55.472Z] DEBUG: 23:19:55.234162 marked file as non-mage: "categories.go"
[2020-11-19T23:19:55.472Z] DEBUG: 23:19:55.234165 marked file as non-mage: "favicon.go"
[2020-11-19T23:19:55.472Z] DEBUG: 23:19:55.234168 marked file as non-mage: "handler.go"
[2020-11-19T23:19:55.472Z] DEBUG: 23:19:55.234171 marked file as non-mage: "index.go"
[2020-11-19T23:19:55.472Z] DEBUG: 23:19:55.234174 marked file as non-mage: "main.go"
[2020-11-19T23:19:55.472Z] DEBUG: 23:19:55.234176 marked file as non-mage: "mime_types.go"
[2020-11-19T23:19:55.472Z] DEBUG: 23:19:55.234179 marked file as non-mage: "package_index.go"
[2020-11-19T23:19:55.472Z] DEBUG: 23:19:55.234182 marked file as non-mage: "search.go"
[2020-11-19T23:19:55.472Z] DEBUG: 23:19:55.234197 marked file as non-mage: "static.go"
[2020-11-19T23:19:55.472Z] DEBUG: 23:19:55.234202 getting all files plus mage files
[2020-11-19T23:19:56.042Z] DEBUG: 23:19:55.843175 time to scan for Magefiles: 888.073189ms
[2020-11-19T23:19:56.042Z] DEBUG: 23:19:55.843194 found magefiles: magefile.go
[2020-11-19T23:19:56.042Z] DEBUG: 23:19:55.847534 output exe is  /var/lib/jenkins/workspace/_manager_package-registry_PR-655/.magefile/5b6fcb0c5231becd550c78b2ae4be9b39747ec1f
[2020-11-19T23:19:56.042Z] DEBUG: 23:19:55.852369 go build cache exists, will ignore any compiled binary
[2020-11-19T23:19:56.042Z] DEBUG: 23:19:55.852386 parsing files
[2020-11-19T23:19:56.042Z] DEBUG: 23:19:55.853093 found target AddLicenseHeaders
[2020-11-19T23:19:56.042Z] DEBUG: 23:19:55.853114 found target Build
[2020-11-19T23:19:56.042Z] DEBUG: 23:19:55.853119 found target Check
[2020-11-19T23:19:56.042Z] DEBUG: 23:19:55.853122 found target Clean
[2020-11-19T23:19:56.042Z] DEBUG: 23:19:55.853125 found target FetchPackageStorage
[2020-11-19T23:19:56.042Z] DEBUG: 23:19:55.853141 skipping function with invalid signature func FindFilesRecursive(match &{4518 0xc0001d8fc0 0xc0001d8ff0})(&{4561 <nil> string}, error)
[2020-11-19T23:19:56.042Z] DEBUG: 23:19:55.853145 found target Format
[2020-11-19T23:19:56.042Z] DEBUG: 23:19:55.853154 found target GoImports
[2020-11-19T23:19:56.042Z] DEBUG: 23:19:55.853165 found target Test
[2020-11-19T23:19:56.042Z] DEBUG: 23:19:55.853170 found target TestIntegration
[2020-11-19T23:19:56.042Z] DEBUG: 23:19:55.853173 found target Vendor
[2020-11-19T23:19:56.042Z] DEBUG: 23:19:55.853189 time parse Magefiles: 793.46µs
[2020-11-19T23:19:56.042Z] DEBUG: 23:19:55.853208 Creating mainfile at mage_output_file.go
[2020-11-19T23:19:56.042Z] DEBUG: 23:19:55.853262 writing new file at mage_output_file.go
[2020-11-19T23:19:56.042Z] DEBUG: 23:19:55.854254 compiling to /var/lib/jenkins/workspace/_manager_package-registry_PR-655/.magefile/5b6fcb0c5231becd550c78b2ae4be9b39747ec1f
[2020-11-19T23:19:56.042Z] DEBUG: 23:19:55.854258 compiling using gocmd: go
[2020-11-19T23:19:56.302Z] DEBUG: 23:19:56.101612 running go build -o /var/lib/jenkins/workspace/_manager_package-registry_PR-655/.magefile/5b6fcb0c5231becd550c78b2ae4be9b39747ec1f magefile.go mage_output_file.go
[2020-11-19T23:19:56.871Z] DEBUG: 23:19:56.651278 time to compile Magefile: 549.612783ms
[2020-11-19T23:19:56.871Z] DEBUG: 23:19:56.651339 running binary /var/lib/j [...]

2020-11-20 07:56 UTC, jalvz approved these changes
thanks!

2020-11-20 08:14 UTC, mtojek requested changes
Could you please add a new test package with relevant data stream to the `testdata/package` directory? You can test it with `go test .`. You will also need to regenerate expected data with `go test . -generate`.

Please also add a CHANGELOG entry.

2020-11-20 19:40 UTC, jen-huang commented
@mtojek Thanks, I added `input_level_templates` test package and updated changelog.

2020-11-20 20:33 UTC, mtojek approved these changes

2020-11-20 20:38 UTC, merged